name: Deploy to Server.
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: 207.148.117.199
        ftp-username: infotech@danirasdalmoth.com
        ftp-password: Daniras@121321
    - name: Install dependencies
      uses: "ramsey/composer-install@v2"
