name: Publish Website to CPanel
on:
  push:
    branches:
      - deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: 207.148.117.199
        ftp-username: infotech@danirasdalmoth.com
        ftp-password: Daniras@121321
    - name: Install dependencies
      uses: "ramsey/composer-install@v2"
